ig.nations =
  "cze" : "Česká republika"
  "fin" : "Finsko"
  "can" : "Kanada"
  "rus" : "Rusko"
  "svk" : "Slovensko"
  "swe" : "Švédsko"
  "sui" : "Švýcarsko"
  "usa" : "Spojené státy"
  "ger" : "Německo"
  "ita" : "Itálie"
  "aut" : "Rakousko"
  "fra" : "Francie"
  "nor" : "Norsko"
  "gbr" : "Velká Británie"
  "lat" : "Litva"
  "blr" : "Bělorusko"
  "jap" : "Japonsko"
  "kaz" : "Kazachstán"
  "ukr" : "Ukrajina"
  "slo" : "Slovinsko"
  "pol" : "Polsko"
  "den" : "Dánsko"
  "hun" : "Maďarsko"
